---
env:
  browser: true
  es6: true
  node: true
  jest: true
settings:
  react:
    pragma: React
    version: latest
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  sourceType: module
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - jest
  - react
  - react-hooks
  - prettier
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jest/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
rules:
  prettier/prettier: error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/prefer-regexp-exec': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unsafe-assignment': warn
  '@typescript-eslint/no-unsafe-member-access': warn
  '@typescript-eslint/no-floating-promises': warn
  '@typescript-eslint/no-unsafe-return': warn # TODO should be commented out
