---
env:
  browser: true
  es6: true
  node: true
parserOptions:
  sourceType: module
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - jest
  - prettier
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
rules:
  prettier/prettier: error
  simple-import-sort/sort: error
