---
env:
  browser: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 7
  sourceType: module
plugins:
  - prettier
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:prettier/recommended
rules:
  prettier/prettier: error
  simple-import-sort/sort: error
