---
env:
  browser: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - simple-import-sort
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
ignorePatterns:
  - src/generated/**/*.ts
  - src/**/*.d.ts
rules:
  prettier/prettier: error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
