version: "3.7"
services:
  database:
    restart: always
    image: "postgres:latest"
    container_name: "postgres"
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - /mnt/postgres/data:/var/lib/postgresql/data
