/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as types from "./../types"
import { QueryComplexity } from "@nexus/schema/dist/plugins/queryComplexityPlugin"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  CategoryCreateInput: { // input type
    name: string; // String!
    posts?: NexusGenInputs['PostCreateManyWithoutCategoriesInput'] | null; // PostCreateManyWithoutCategoriesInput
  }
  CategoryCreateManyWithoutPostsInput: { // input type
    connect?: NexusGenInputs['CategoryWhereUniqueInput'][] | null; // [CategoryWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CategoryCreateOrConnectWithoutpostsInput'][] | null; // [CategoryCreateOrConnectWithoutpostsInput!]
    create?: NexusGenInputs['CategoryCreateWithoutPostsInput'][] | null; // [CategoryCreateWithoutPostsInput!]
  }
  CategoryCreateOrConnectWithoutpostsInput: { // input type
    create: NexusGenInputs['CategoryCreateWithoutPostsInput']; // CategoryCreateWithoutPostsInput!
    where: NexusGenInputs['CategoryWhereUniqueInput']; // CategoryWhereUniqueInput!
  }
  CategoryCreateWithoutPostsInput: { // input type
    name: string; // String!
  }
  CategoryListRelationFilter: { // input type
    every?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
    none?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
    some?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
  }
  CategoryOrderByInput: { // input type
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  CategoryScalarWhereInput: { // input type
    AND?: NexusGenInputs['CategoryScalarWhereInput'][] | null; // [CategoryScalarWhereInput!]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['CategoryScalarWhereInput'][] | null; // [CategoryScalarWhereInput!]
    OR?: NexusGenInputs['CategoryScalarWhereInput'][] | null; // [CategoryScalarWhereInput!]
  }
  CategoryUpdateInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutCategoriesInput'] | null; // PostUpdateManyWithoutCategoriesInput
  }
  CategoryUpdateManyMutationInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  CategoryUpdateManyWithWhereWithoutPostsInput: { // input type
    data: NexusGenInputs['CategoryUpdateManyMutationInput']; // CategoryUpdateManyMutationInput!
    where: NexusGenInputs['CategoryScalarWhereInput']; // CategoryScalarWhereInput!
  }
  CategoryUpdateManyWithoutPostsInput: { // input type
    connect?: NexusGenInputs['CategoryWhereUniqueInput'][] | null; // [CategoryWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CategoryCreateOrConnectWithoutpostsInput'][] | null; // [CategoryCreateOrConnectWithoutpostsInput!]
    create?: NexusGenInputs['CategoryCreateWithoutPostsInput'][] | null; // [CategoryCreateWithoutPostsInput!]
    delete?: NexusGenInputs['CategoryWhereUniqueInput'][] | null; // [CategoryWhereUniqueInput!]
    deleteMany?: NexusGenInputs['CategoryScalarWhereInput'][] | null; // [CategoryScalarWhereInput!]
    disconnect?: NexusGenInputs['CategoryWhereUniqueInput'][] | null; // [CategoryWhereUniqueInput!]
    set?: NexusGenInputs['CategoryWhereUniqueInput'][] | null; // [CategoryWhereUniqueInput!]
    update?: NexusGenInputs['CategoryUpdateWithWhereUniqueWithoutPostsInput'][] | null; // [CategoryUpdateWithWhereUniqueWithoutPostsInput!]
    updateMany?: NexusGenInputs['CategoryUpdateManyWithWhereWithoutPostsInput'][] | null; // [CategoryUpdateManyWithWhereWithoutPostsInput!]
    upsert?: NexusGenInputs['CategoryUpsertWithWhereUniqueWithoutPostsInput'][] | null; // [CategoryUpsertWithWhereUniqueWithoutPostsInput!]
  }
  CategoryUpdateWithWhereUniqueWithoutPostsInput: { // input type
    data: NexusGenInputs['CategoryUpdateWithoutPostsInput']; // CategoryUpdateWithoutPostsInput!
    where: NexusGenInputs['CategoryWhereUniqueInput']; // CategoryWhereUniqueInput!
  }
  CategoryUpdateWithoutPostsInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  CategoryUpsertWithWhereUniqueWithoutPostsInput: { // input type
    create: NexusGenInputs['CategoryCreateWithoutPostsInput']; // CategoryCreateWithoutPostsInput!
    update: NexusGenInputs['CategoryUpdateWithoutPostsInput']; // CategoryUpdateWithoutPostsInput!
    where: NexusGenInputs['CategoryWhereUniqueInput']; // CategoryWhereUniqueInput!
  }
  CategoryWhereInput: { // input type
    AND?: NexusGenInputs['CategoryWhereInput'][] | null; // [CategoryWhereInput!]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['CategoryWhereInput'][] | null; // [CategoryWhereInput!]
    OR?: NexusGenInputs['CategoryWhereInput'][] | null; // [CategoryWhereInput!]
    posts?: NexusGenInputs['PostListRelationFilter'] | null; // PostListRelationFilter
  }
  CategoryWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  CommentCreateInput: { // input type
    content?: string | null; // String
    post?: NexusGenInputs['PostCreateOneWithoutCommentsInput'] | null; // PostCreateOneWithoutCommentsInput
    title: string; // String!
  }
  CommentCreateManyWithoutPostInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutpostInput'][] | null; // [CommentCreateOrConnectWithoutpostInput!]
    create?: NexusGenInputs['CommentCreateWithoutPostInput'][] | null; // [CommentCreateWithoutPostInput!]
  }
  CommentCreateOrConnectWithoutpostInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutPostInput']; // CommentCreateWithoutPostInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentCreateWithoutPostInput: { // input type
    content?: string | null; // String
    title: string; // String!
  }
  CommentListRelationFilter: { // input type
    every?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
    none?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
    some?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
  }
  CommentOrderByInput: { // input type
    content?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    postId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    title?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  CommentScalarWhereInput: { // input type
    AND?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    content?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    OR?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    postId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  CommentUpdateInput: { // input type
    content?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    post?: NexusGenInputs['PostUpdateOneWithoutCommentsInput'] | null; // PostUpdateOneWithoutCommentsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  CommentUpdateManyMutationInput: { // input type
    content?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  CommentUpdateManyWithWhereWithoutPostInput: { // input type
    data: NexusGenInputs['CommentUpdateManyMutationInput']; // CommentUpdateManyMutationInput!
    where: NexusGenInputs['CommentScalarWhereInput']; // CommentScalarWhereInput!
  }
  CommentUpdateManyWithoutPostInput: { // input type
    connect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CommentCreateOrConnectWithoutpostInput'][] | null; // [CommentCreateOrConnectWithoutpostInput!]
    create?: NexusGenInputs['CommentCreateWithoutPostInput'][] | null; // [CommentCreateWithoutPostInput!]
    delete?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    deleteMany?: NexusGenInputs['CommentScalarWhereInput'][] | null; // [CommentScalarWhereInput!]
    disconnect?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    set?: NexusGenInputs['CommentWhereUniqueInput'][] | null; // [CommentWhereUniqueInput!]
    update?: NexusGenInputs['CommentUpdateWithWhereUniqueWithoutPostInput'][] | null; // [CommentUpdateWithWhereUniqueWithoutPostInput!]
    updateMany?: NexusGenInputs['CommentUpdateManyWithWhereWithoutPostInput'][] | null; // [CommentUpdateManyWithWhereWithoutPostInput!]
    upsert?: NexusGenInputs['CommentUpsertWithWhereUniqueWithoutPostInput'][] | null; // [CommentUpsertWithWhereUniqueWithoutPostInput!]
  }
  CommentUpdateWithWhereUniqueWithoutPostInput: { // input type
    data: NexusGenInputs['CommentUpdateWithoutPostInput']; // CommentUpdateWithoutPostInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentUpdateWithoutPostInput: { // input type
    content?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  CommentUpsertWithWhereUniqueWithoutPostInput: { // input type
    create: NexusGenInputs['CommentCreateWithoutPostInput']; // CommentCreateWithoutPostInput!
    update: NexusGenInputs['CommentUpdateWithoutPostInput']; // CommentUpdateWithoutPostInput!
    where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
  }
  CommentWhereInput: { // input type
    AND?: NexusGenInputs['CommentWhereInput'][] | null; // [CommentWhereInput!]
    content?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['CommentWhereInput'][] | null; // [CommentWhereInput!]
    OR?: NexusGenInputs['CommentWhereInput'][] | null; // [CommentWhereInput!]
    post?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    postId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  CommentWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  EnumRoleFieldUpdateOperationsInput: { // input type
    set?: NexusGenEnums['Role'] | null; // Role
  }
  EnumRoleFilter: { // input type
    equals?: NexusGenEnums['Role'] | null; // Role
    in?: NexusGenEnums['Role'][] | null; // [Role!]
    not?: NexusGenInputs['NestedEnumRoleFilter'] | null; // NestedEnumRoleFilter
    notIn?: NexusGenEnums['Role'][] | null; // [Role!]
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedEnumRoleFilter: { // input type
    equals?: NexusGenEnums['Role'] | null; // Role
    in?: NexusGenEnums['Role'][] | null; // [Role!]
    not?: NexusGenInputs['NestedEnumRoleFilter'] | null; // NestedEnumRoleFilter
    notIn?: NexusGenEnums['Role'][] | null; // [Role!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  PostCreateInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutPostsInput'] | null; // UserCreateOneWithoutPostsInput
    categories?: NexusGenInputs['CategoryCreateManyWithoutPostsInput'] | null; // CategoryCreateManyWithoutPostsInput
    comments?: NexusGenInputs['CommentCreateManyWithoutPostInput'] | null; // CommentCreateManyWithoutPostInput
    content?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    keywords?: NexusGenInputs['PostCreatekeywordsInput'] | null; // PostCreatekeywordsInput
    published?: boolean | null; // Boolean
    tags?: NexusGenInputs['TagCreateManyWithoutPostsInput'] | null; // TagCreateManyWithoutPostsInput
    title: string; // String!
  }
  PostCreateManyWithoutAuthorInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutauthorInput'][] | null; // [PostCreateOrConnectWithoutauthorInput!]
    create?: NexusGenInputs['PostCreateWithoutAuthorInput'][] | null; // [PostCreateWithoutAuthorInput!]
  }
  PostCreateManyWithoutCategoriesInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutcategoriesInput'][] | null; // [PostCreateOrConnectWithoutcategoriesInput!]
    create?: NexusGenInputs['PostCreateWithoutCategoriesInput'][] | null; // [PostCreateWithoutCategoriesInput!]
  }
  PostCreateManyWithoutTagsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithouttagsInput'][] | null; // [PostCreateOrConnectWithouttagsInput!]
    create?: NexusGenInputs['PostCreateWithoutTagsInput'][] | null; // [PostCreateWithoutTagsInput!]
  }
  PostCreateOneWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutcommentsInput'] | null; // PostCreateOrConnectWithoutcommentsInput
    create?: NexusGenInputs['PostCreateWithoutCommentsInput'] | null; // PostCreateWithoutCommentsInput
  }
  PostCreateOrConnectWithoutauthorInput: { // input type
    create: NexusGenInputs['PostCreateWithoutAuthorInput']; // PostCreateWithoutAuthorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateOrConnectWithoutcategoriesInput: { // input type
    create: NexusGenInputs['PostCreateWithoutCategoriesInput']; // PostCreateWithoutCategoriesInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateOrConnectWithoutcommentsInput: { // input type
    create: NexusGenInputs['PostCreateWithoutCommentsInput']; // PostCreateWithoutCommentsInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateOrConnectWithouttagsInput: { // input type
    create: NexusGenInputs['PostCreateWithoutTagsInput']; // PostCreateWithoutTagsInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateWithoutAuthorInput: { // input type
    categories?: NexusGenInputs['CategoryCreateManyWithoutPostsInput'] | null; // CategoryCreateManyWithoutPostsInput
    comments?: NexusGenInputs['CommentCreateManyWithoutPostInput'] | null; // CommentCreateManyWithoutPostInput
    content?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    keywords?: NexusGenInputs['PostCreatekeywordsInput'] | null; // PostCreatekeywordsInput
    published?: boolean | null; // Boolean
    tags?: NexusGenInputs['TagCreateManyWithoutPostsInput'] | null; // TagCreateManyWithoutPostsInput
    title: string; // String!
  }
  PostCreateWithoutCategoriesInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutPostsInput'] | null; // UserCreateOneWithoutPostsInput
    comments?: NexusGenInputs['CommentCreateManyWithoutPostInput'] | null; // CommentCreateManyWithoutPostInput
    content?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    keywords?: NexusGenInputs['PostCreatekeywordsInput'] | null; // PostCreatekeywordsInput
    published?: boolean | null; // Boolean
    tags?: NexusGenInputs['TagCreateManyWithoutPostsInput'] | null; // TagCreateManyWithoutPostsInput
    title: string; // String!
  }
  PostCreateWithoutCommentsInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutPostsInput'] | null; // UserCreateOneWithoutPostsInput
    categories?: NexusGenInputs['CategoryCreateManyWithoutPostsInput'] | null; // CategoryCreateManyWithoutPostsInput
    content?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    keywords?: NexusGenInputs['PostCreatekeywordsInput'] | null; // PostCreatekeywordsInput
    published?: boolean | null; // Boolean
    tags?: NexusGenInputs['TagCreateManyWithoutPostsInput'] | null; // TagCreateManyWithoutPostsInput
    title: string; // String!
  }
  PostCreateWithoutTagsInput: { // input type
    author?: NexusGenInputs['UserCreateOneWithoutPostsInput'] | null; // UserCreateOneWithoutPostsInput
    categories?: NexusGenInputs['CategoryCreateManyWithoutPostsInput'] | null; // CategoryCreateManyWithoutPostsInput
    comments?: NexusGenInputs['CommentCreateManyWithoutPostInput'] | null; // CommentCreateManyWithoutPostInput
    content?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    keywords?: NexusGenInputs['PostCreatekeywordsInput'] | null; // PostCreatekeywordsInput
    published?: boolean | null; // Boolean
    title: string; // String!
  }
  PostCreatekeywordsInput: { // input type
    set?: string[] | null; // [String!]
  }
  PostListRelationFilter: { // input type
    every?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    none?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    some?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
  }
  PostOrderByInput: { // input type
    authorId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    content?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    keywords?: NexusGenEnums['SortOrder'] | null; // SortOrder
    published?: NexusGenEnums['SortOrder'] | null; // SortOrder
    title?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  PostScalarWhereInput: { // input type
    AND?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    authorId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    content?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    keywords?: NexusGenInputs['StringNullableListFilter'] | null; // StringNullableListFilter
    NOT?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    OR?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  PostUpdateInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutPostsInput'] | null; // UserUpdateOneWithoutPostsInput
    categories?: NexusGenInputs['CategoryUpdateManyWithoutPostsInput'] | null; // CategoryUpdateManyWithoutPostsInput
    comments?: NexusGenInputs['CommentUpdateManyWithoutPostInput'] | null; // CommentUpdateManyWithoutPostInput
    content?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    keywords?: NexusGenInputs['PostUpdatekeywordsInput'] | null; // PostUpdatekeywordsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    tags?: NexusGenInputs['TagUpdateManyWithoutPostsInput'] | null; // TagUpdateManyWithoutPostsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  PostUpdateManyMutationInput: { // input type
    content?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    keywords?: NexusGenInputs['PostUpdatekeywordsInput'] | null; // PostUpdatekeywordsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  PostUpdateManyWithWhereWithoutAuthorInput: { // input type
    data: NexusGenInputs['PostUpdateManyMutationInput']; // PostUpdateManyMutationInput!
    where: NexusGenInputs['PostScalarWhereInput']; // PostScalarWhereInput!
  }
  PostUpdateManyWithWhereWithoutCategoriesInput: { // input type
    data: NexusGenInputs['PostUpdateManyMutationInput']; // PostUpdateManyMutationInput!
    where: NexusGenInputs['PostScalarWhereInput']; // PostScalarWhereInput!
  }
  PostUpdateManyWithWhereWithoutTagsInput: { // input type
    data: NexusGenInputs['PostUpdateManyMutationInput']; // PostUpdateManyMutationInput!
    where: NexusGenInputs['PostScalarWhereInput']; // PostScalarWhereInput!
  }
  PostUpdateManyWithoutAuthorInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutauthorInput'][] | null; // [PostCreateOrConnectWithoutauthorInput!]
    create?: NexusGenInputs['PostCreateWithoutAuthorInput'][] | null; // [PostCreateWithoutAuthorInput!]
    delete?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    deleteMany?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    disconnect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    set?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    update?: NexusGenInputs['PostUpdateWithWhereUniqueWithoutAuthorInput'][] | null; // [PostUpdateWithWhereUniqueWithoutAuthorInput!]
    updateMany?: NexusGenInputs['PostUpdateManyWithWhereWithoutAuthorInput'][] | null; // [PostUpdateManyWithWhereWithoutAuthorInput!]
    upsert?: NexusGenInputs['PostUpsertWithWhereUniqueWithoutAuthorInput'][] | null; // [PostUpsertWithWhereUniqueWithoutAuthorInput!]
  }
  PostUpdateManyWithoutCategoriesInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutcategoriesInput'][] | null; // [PostCreateOrConnectWithoutcategoriesInput!]
    create?: NexusGenInputs['PostCreateWithoutCategoriesInput'][] | null; // [PostCreateWithoutCategoriesInput!]
    delete?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    deleteMany?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    disconnect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    set?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    update?: NexusGenInputs['PostUpdateWithWhereUniqueWithoutCategoriesInput'][] | null; // [PostUpdateWithWhereUniqueWithoutCategoriesInput!]
    updateMany?: NexusGenInputs['PostUpdateManyWithWhereWithoutCategoriesInput'][] | null; // [PostUpdateManyWithWhereWithoutCategoriesInput!]
    upsert?: NexusGenInputs['PostUpsertWithWhereUniqueWithoutCategoriesInput'][] | null; // [PostUpsertWithWhereUniqueWithoutCategoriesInput!]
  }
  PostUpdateManyWithoutTagsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithouttagsInput'][] | null; // [PostCreateOrConnectWithouttagsInput!]
    create?: NexusGenInputs['PostCreateWithoutTagsInput'][] | null; // [PostCreateWithoutTagsInput!]
    delete?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    deleteMany?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    disconnect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    set?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    update?: NexusGenInputs['PostUpdateWithWhereUniqueWithoutTagsInput'][] | null; // [PostUpdateWithWhereUniqueWithoutTagsInput!]
    updateMany?: NexusGenInputs['PostUpdateManyWithWhereWithoutTagsInput'][] | null; // [PostUpdateManyWithWhereWithoutTagsInput!]
    upsert?: NexusGenInputs['PostUpsertWithWhereUniqueWithoutTagsInput'][] | null; // [PostUpsertWithWhereUniqueWithoutTagsInput!]
  }
  PostUpdateOneWithoutCommentsInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutcommentsInput'] | null; // PostCreateOrConnectWithoutcommentsInput
    create?: NexusGenInputs['PostCreateWithoutCommentsInput'] | null; // PostCreateWithoutCommentsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['PostUpdateWithoutCommentsInput'] | null; // PostUpdateWithoutCommentsInput
    upsert?: NexusGenInputs['PostUpsertWithoutCommentsInput'] | null; // PostUpsertWithoutCommentsInput
  }
  PostUpdateWithWhereUniqueWithoutAuthorInput: { // input type
    data: NexusGenInputs['PostUpdateWithoutAuthorInput']; // PostUpdateWithoutAuthorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpdateWithWhereUniqueWithoutCategoriesInput: { // input type
    data: NexusGenInputs['PostUpdateWithoutCategoriesInput']; // PostUpdateWithoutCategoriesInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpdateWithWhereUniqueWithoutTagsInput: { // input type
    data: NexusGenInputs['PostUpdateWithoutTagsInput']; // PostUpdateWithoutTagsInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpdateWithoutAuthorInput: { // input type
    categories?: NexusGenInputs['CategoryUpdateManyWithoutPostsInput'] | null; // CategoryUpdateManyWithoutPostsInput
    comments?: NexusGenInputs['CommentUpdateManyWithoutPostInput'] | null; // CommentUpdateManyWithoutPostInput
    content?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    keywords?: NexusGenInputs['PostUpdatekeywordsInput'] | null; // PostUpdatekeywordsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    tags?: NexusGenInputs['TagUpdateManyWithoutPostsInput'] | null; // TagUpdateManyWithoutPostsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  PostUpdateWithoutCategoriesInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutPostsInput'] | null; // UserUpdateOneWithoutPostsInput
    comments?: NexusGenInputs['CommentUpdateManyWithoutPostInput'] | null; // CommentUpdateManyWithoutPostInput
    content?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    keywords?: NexusGenInputs['PostUpdatekeywordsInput'] | null; // PostUpdatekeywordsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    tags?: NexusGenInputs['TagUpdateManyWithoutPostsInput'] | null; // TagUpdateManyWithoutPostsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  PostUpdateWithoutCommentsInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutPostsInput'] | null; // UserUpdateOneWithoutPostsInput
    categories?: NexusGenInputs['CategoryUpdateManyWithoutPostsInput'] | null; // CategoryUpdateManyWithoutPostsInput
    content?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    keywords?: NexusGenInputs['PostUpdatekeywordsInput'] | null; // PostUpdatekeywordsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    tags?: NexusGenInputs['TagUpdateManyWithoutPostsInput'] | null; // TagUpdateManyWithoutPostsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  PostUpdateWithoutTagsInput: { // input type
    author?: NexusGenInputs['UserUpdateOneWithoutPostsInput'] | null; // UserUpdateOneWithoutPostsInput
    categories?: NexusGenInputs['CategoryUpdateManyWithoutPostsInput'] | null; // CategoryUpdateManyWithoutPostsInput
    comments?: NexusGenInputs['CommentUpdateManyWithoutPostInput'] | null; // CommentUpdateManyWithoutPostInput
    content?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    keywords?: NexusGenInputs['PostUpdatekeywordsInput'] | null; // PostUpdatekeywordsInput
    published?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  PostUpdatekeywordsInput: { // input type
    set?: string[] | null; // [String!]
  }
  PostUpsertWithWhereUniqueWithoutAuthorInput: { // input type
    create: NexusGenInputs['PostCreateWithoutAuthorInput']; // PostCreateWithoutAuthorInput!
    update: NexusGenInputs['PostUpdateWithoutAuthorInput']; // PostUpdateWithoutAuthorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpsertWithWhereUniqueWithoutCategoriesInput: { // input type
    create: NexusGenInputs['PostCreateWithoutCategoriesInput']; // PostCreateWithoutCategoriesInput!
    update: NexusGenInputs['PostUpdateWithoutCategoriesInput']; // PostUpdateWithoutCategoriesInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpsertWithWhereUniqueWithoutTagsInput: { // input type
    create: NexusGenInputs['PostCreateWithoutTagsInput']; // PostCreateWithoutTagsInput!
    update: NexusGenInputs['PostUpdateWithoutTagsInput']; // PostUpdateWithoutTagsInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpsertWithoutCommentsInput: { // input type
    create: NexusGenInputs['PostCreateWithoutCommentsInput']; // PostCreateWithoutCommentsInput!
    update: NexusGenInputs['PostUpdateWithoutCommentsInput']; // PostUpdateWithoutCommentsInput!
  }
  PostWhereInput: { // input type
    AND?: NexusGenInputs['PostWhereInput'][] | null; // [PostWhereInput!]
    author?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    authorId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    categories?: NexusGenInputs['CategoryListRelationFilter'] | null; // CategoryListRelationFilter
    comments?: NexusGenInputs['CommentListRelationFilter'] | null; // CommentListRelationFilter
    content?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    keywords?: NexusGenInputs['StringNullableListFilter'] | null; // StringNullableListFilter
    NOT?: NexusGenInputs['PostWhereInput'][] | null; // [PostWhereInput!]
    OR?: NexusGenInputs['PostWhereInput'][] | null; // [PostWhereInput!]
    published?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    tags?: NexusGenInputs['TagListRelationFilter'] | null; // TagListRelationFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  PostWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  ProfileCreateInput: { // input type
    bio: string; // String!
    user: NexusGenInputs['UserCreateOneWithoutProfileInput']; // UserCreateOneWithoutProfileInput!
  }
  ProfileCreateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['ProfileWhereUniqueInput'] | null; // ProfileWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProfileCreateOrConnectWithoutuserInput'] | null; // ProfileCreateOrConnectWithoutuserInput
    create?: NexusGenInputs['ProfileCreateWithoutUserInput'] | null; // ProfileCreateWithoutUserInput
  }
  ProfileCreateOrConnectWithoutuserInput: { // input type
    create: NexusGenInputs['ProfileCreateWithoutUserInput']; // ProfileCreateWithoutUserInput!
    where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
  }
  ProfileCreateWithoutUserInput: { // input type
    bio: string; // String!
  }
  ProfileOrderByInput: { // input type
    bio?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    userId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ProfileUpdateInput: { // input type
    bio?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    user?: NexusGenInputs['UserUpdateOneRequiredWithoutProfileInput'] | null; // UserUpdateOneRequiredWithoutProfileInput
  }
  ProfileUpdateManyMutationInput: { // input type
    bio?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  ProfileUpdateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['ProfileWhereUniqueInput'] | null; // ProfileWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProfileCreateOrConnectWithoutuserInput'] | null; // ProfileCreateOrConnectWithoutuserInput
    create?: NexusGenInputs['ProfileCreateWithoutUserInput'] | null; // ProfileCreateWithoutUserInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['ProfileUpdateWithoutUserInput'] | null; // ProfileUpdateWithoutUserInput
    upsert?: NexusGenInputs['ProfileUpsertWithoutUserInput'] | null; // ProfileUpsertWithoutUserInput
  }
  ProfileUpdateWithoutUserInput: { // input type
    bio?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  ProfileUpsertWithoutUserInput: { // input type
    create: NexusGenInputs['ProfileCreateWithoutUserInput']; // ProfileCreateWithoutUserInput!
    update: NexusGenInputs['ProfileUpdateWithoutUserInput']; // ProfileUpdateWithoutUserInput!
  }
  ProfileWhereInput: { // input type
    AND?: NexusGenInputs['ProfileWhereInput'][] | null; // [ProfileWhereInput!]
    bio?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['ProfileWhereInput'][] | null; // [ProfileWhereInput!]
    OR?: NexusGenInputs['ProfileWhereInput'][] | null; // [ProfileWhereInput!]
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    userId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  ProfileWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableListFilter: { // input type
    equals?: string[] | null; // [String!]
  }
  TagCreateInput: { // input type
    name: string; // String!
    posts?: NexusGenInputs['PostCreateManyWithoutTagsInput'] | null; // PostCreateManyWithoutTagsInput
  }
  TagCreateManyWithoutPostsInput: { // input type
    connect?: NexusGenInputs['TagWhereUniqueInput'][] | null; // [TagWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['TagCreateOrConnectWithoutpostsInput'][] | null; // [TagCreateOrConnectWithoutpostsInput!]
    create?: NexusGenInputs['TagCreateWithoutPostsInput'][] | null; // [TagCreateWithoutPostsInput!]
  }
  TagCreateOrConnectWithoutpostsInput: { // input type
    create: NexusGenInputs['TagCreateWithoutPostsInput']; // TagCreateWithoutPostsInput!
    where: NexusGenInputs['TagWhereUniqueInput']; // TagWhereUniqueInput!
  }
  TagCreateWithoutPostsInput: { // input type
    name: string; // String!
  }
  TagListRelationFilter: { // input type
    every?: NexusGenInputs['TagWhereInput'] | null; // TagWhereInput
    none?: NexusGenInputs['TagWhereInput'] | null; // TagWhereInput
    some?: NexusGenInputs['TagWhereInput'] | null; // TagWhereInput
  }
  TagOrderByInput: { // input type
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  TagScalarWhereInput: { // input type
    AND?: NexusGenInputs['TagScalarWhereInput'][] | null; // [TagScalarWhereInput!]
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['TagScalarWhereInput'][] | null; // [TagScalarWhereInput!]
    OR?: NexusGenInputs['TagScalarWhereInput'][] | null; // [TagScalarWhereInput!]
  }
  TagUpdateInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutTagsInput'] | null; // PostUpdateManyWithoutTagsInput
  }
  TagUpdateManyMutationInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  TagUpdateManyWithWhereWithoutPostsInput: { // input type
    data: NexusGenInputs['TagUpdateManyMutationInput']; // TagUpdateManyMutationInput!
    where: NexusGenInputs['TagScalarWhereInput']; // TagScalarWhereInput!
  }
  TagUpdateManyWithoutPostsInput: { // input type
    connect?: NexusGenInputs['TagWhereUniqueInput'][] | null; // [TagWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['TagCreateOrConnectWithoutpostsInput'][] | null; // [TagCreateOrConnectWithoutpostsInput!]
    create?: NexusGenInputs['TagCreateWithoutPostsInput'][] | null; // [TagCreateWithoutPostsInput!]
    delete?: NexusGenInputs['TagWhereUniqueInput'][] | null; // [TagWhereUniqueInput!]
    deleteMany?: NexusGenInputs['TagScalarWhereInput'][] | null; // [TagScalarWhereInput!]
    disconnect?: NexusGenInputs['TagWhereUniqueInput'][] | null; // [TagWhereUniqueInput!]
    set?: NexusGenInputs['TagWhereUniqueInput'][] | null; // [TagWhereUniqueInput!]
    update?: NexusGenInputs['TagUpdateWithWhereUniqueWithoutPostsInput'][] | null; // [TagUpdateWithWhereUniqueWithoutPostsInput!]
    updateMany?: NexusGenInputs['TagUpdateManyWithWhereWithoutPostsInput'][] | null; // [TagUpdateManyWithWhereWithoutPostsInput!]
    upsert?: NexusGenInputs['TagUpsertWithWhereUniqueWithoutPostsInput'][] | null; // [TagUpsertWithWhereUniqueWithoutPostsInput!]
  }
  TagUpdateWithWhereUniqueWithoutPostsInput: { // input type
    data: NexusGenInputs['TagUpdateWithoutPostsInput']; // TagUpdateWithoutPostsInput!
    where: NexusGenInputs['TagWhereUniqueInput']; // TagWhereUniqueInput!
  }
  TagUpdateWithoutPostsInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  TagUpsertWithWhereUniqueWithoutPostsInput: { // input type
    create: NexusGenInputs['TagCreateWithoutPostsInput']; // TagCreateWithoutPostsInput!
    update: NexusGenInputs['TagUpdateWithoutPostsInput']; // TagUpdateWithoutPostsInput!
    where: NexusGenInputs['TagWhereUniqueInput']; // TagWhereUniqueInput!
  }
  TagWhereInput: { // input type
    AND?: NexusGenInputs['TagWhereInput'][] | null; // [TagWhereInput!]
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['TagWhereInput'][] | null; // [TagWhereInput!]
    OR?: NexusGenInputs['TagWhereInput'][] | null; // [TagWhereInput!]
    posts?: NexusGenInputs['PostListRelationFilter'] | null; // PostListRelationFilter
  }
  TagWhereUniqueInput: { // input type
    name?: string | null; // String
  }
  UserCreateInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    posts?: NexusGenInputs['PostCreateManyWithoutAuthorInput'] | null; // PostCreateManyWithoutAuthorInput
    profile?: NexusGenInputs['ProfileCreateOneWithoutUserInput'] | null; // ProfileCreateOneWithoutUserInput
    role?: NexusGenEnums['Role'] | null; // Role
  }
  UserCreateOneWithoutPostsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutpostsInput'] | null; // UserCreateOrConnectWithoutpostsInput
    create?: NexusGenInputs['UserCreateWithoutPostsInput'] | null; // UserCreateWithoutPostsInput
  }
  UserCreateOneWithoutProfileInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutprofileInput'] | null; // UserCreateOrConnectWithoutprofileInput
    create?: NexusGenInputs['UserCreateWithoutProfileInput'] | null; // UserCreateWithoutProfileInput
  }
  UserCreateOrConnectWithoutpostsInput: { // input type
    create: NexusGenInputs['UserCreateWithoutPostsInput']; // UserCreateWithoutPostsInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateOrConnectWithoutprofileInput: { // input type
    create: NexusGenInputs['UserCreateWithoutProfileInput']; // UserCreateWithoutProfileInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateWithoutPostsInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    profile?: NexusGenInputs['ProfileCreateOneWithoutUserInput'] | null; // ProfileCreateOneWithoutUserInput
    role?: NexusGenEnums['Role'] | null; // Role
  }
  UserCreateWithoutProfileInput: { // input type
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    posts?: NexusGenInputs['PostCreateManyWithoutAuthorInput'] | null; // PostCreateManyWithoutAuthorInput
    role?: NexusGenEnums['Role'] | null; // Role
  }
  UserOrderByInput: { // input type
    email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    firstName?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    lastName?: NexusGenEnums['SortOrder'] | null; // SortOrder
    role?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserUpdateInput: { // input type
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutAuthorInput'] | null; // PostUpdateManyWithoutAuthorInput
    profile?: NexusGenInputs['ProfileUpdateOneWithoutUserInput'] | null; // ProfileUpdateOneWithoutUserInput
    role?: NexusGenInputs['EnumRoleFieldUpdateOperationsInput'] | null; // EnumRoleFieldUpdateOperationsInput
  }
  UserUpdateManyMutationInput: { // input type
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    role?: NexusGenInputs['EnumRoleFieldUpdateOperationsInput'] | null; // EnumRoleFieldUpdateOperationsInput
  }
  UserUpdateOneRequiredWithoutProfileInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutprofileInput'] | null; // UserCreateOrConnectWithoutprofileInput
    create?: NexusGenInputs['UserCreateWithoutProfileInput'] | null; // UserCreateWithoutProfileInput
    update?: NexusGenInputs['UserUpdateWithoutProfileInput'] | null; // UserUpdateWithoutProfileInput
    upsert?: NexusGenInputs['UserUpsertWithoutProfileInput'] | null; // UserUpsertWithoutProfileInput
  }
  UserUpdateOneWithoutPostsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutpostsInput'] | null; // UserCreateOrConnectWithoutpostsInput
    create?: NexusGenInputs['UserCreateWithoutPostsInput'] | null; // UserCreateWithoutPostsInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['UserUpdateWithoutPostsInput'] | null; // UserUpdateWithoutPostsInput
    upsert?: NexusGenInputs['UserUpsertWithoutPostsInput'] | null; // UserUpsertWithoutPostsInput
  }
  UserUpdateWithoutPostsInput: { // input type
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    profile?: NexusGenInputs['ProfileUpdateOneWithoutUserInput'] | null; // ProfileUpdateOneWithoutUserInput
    role?: NexusGenInputs['EnumRoleFieldUpdateOperationsInput'] | null; // EnumRoleFieldUpdateOperationsInput
  }
  UserUpdateWithoutProfileInput: { // input type
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    firstName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    lastName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutAuthorInput'] | null; // PostUpdateManyWithoutAuthorInput
    role?: NexusGenInputs['EnumRoleFieldUpdateOperationsInput'] | null; // EnumRoleFieldUpdateOperationsInput
  }
  UserUpsertWithoutPostsInput: { // input type
    create: NexusGenInputs['UserCreateWithoutPostsInput']; // UserCreateWithoutPostsInput!
    update: NexusGenInputs['UserUpdateWithoutPostsInput']; // UserUpdateWithoutPostsInput!
  }
  UserUpsertWithoutProfileInput: { // input type
    create: NexusGenInputs['UserCreateWithoutProfileInput']; // UserCreateWithoutProfileInput!
    update: NexusGenInputs['UserUpdateWithoutProfileInput']; // UserUpdateWithoutProfileInput!
  }
  UserWhereInput: { // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    firstName?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    lastName?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    posts?: NexusGenInputs['PostListRelationFilter'] | null; // PostListRelationFilter
    profile?: NexusGenInputs['ProfileWhereInput'] | null; // ProfileWhereInput
    role?: NexusGenInputs['EnumRoleFilter'] | null; // EnumRoleFilter
  }
  UserWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
  Role: "ADMIN" | "USER"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  BatchPayload: { // root type
    count: number; // Int!
  }
  Category: { // root type
    id: number; // Int!
    name: string; // String!
  }
  Comment: { // root type
    content?: string | null; // String
    id: number; // Int!
    postId?: number | null; // Int
    title: string; // String!
  }
  Mutation: {};
  Post: { // root type
    authorId?: number | null; // Int
    content?: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    keywords: string[]; // [String!]!
    published: boolean; // Boolean!
    title: string; // String!
  }
  Profile: { // root type
    bio: string; // String!
    id: number; // Int!
  }
  Query: {};
  Tag: { // root type
    name: string; // String!
  }
  User: { // root type
    email: string; // String!
    firstName: string; // String!
    id: number; // Int!
    lastName: string; // String!
    role: NexusGenEnums['Role']; // Role!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  BatchPayload: { // field return type
    count: number; // Int!
  }
  Category: { // field return type
    id: number; // Int!
    name: string; // String!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
  }
  Comment: { // field return type
    content: string | null; // String
    id: number; // Int!
    post: NexusGenRootTypes['Post'] | null; // Post
    postId: number | null; // Int
    title: string; // String!
  }
  Mutation: { // field return type
    createCategory: NexusGenRootTypes['Category']; // Category!
    createComment: NexusGenRootTypes['Comment']; // Comment!
    createDraft: NexusGenRootTypes['Post'] | null; // Post
    createPost: NexusGenRootTypes['Post']; // Post!
    createProfile: NexusGenRootTypes['Profile']; // Profile!
    createTag: NexusGenRootTypes['Tag']; // Tag!
    createUser: NexusGenRootTypes['User']; // User!
    deleteCategories: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteCategory: NexusGenRootTypes['Category'] | null; // Category
    deleteComment: NexusGenRootTypes['Comment'] | null; // Comment
    deleteComments: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deletePost: NexusGenRootTypes['Post'] | null; // Post
    deletePosts: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteProfile: NexusGenRootTypes['Profile'] | null; // Profile
    deleteProfiles: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteTag: NexusGenRootTypes['Tag'] | null; // Tag
    deleteTags: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteUser: NexusGenRootTypes['User'] | null; // User
    deleteUsers: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateCategories: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateCategory: NexusGenRootTypes['Category'] | null; // Category
    updateComment: NexusGenRootTypes['Comment'] | null; // Comment
    updateComments: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updatePost: NexusGenRootTypes['Post'] | null; // Post
    updatePosts: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateProfile: NexusGenRootTypes['Profile'] | null; // Profile
    updateProfiles: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateTag: NexusGenRootTypes['Tag'] | null; // Tag
    updateTags: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    updateUser: NexusGenRootTypes['User'] | null; // User
    updateUsers: NexusGenRootTypes['BatchPayload']; // BatchPayload!
  }
  Post: { // field return type
    author: NexusGenRootTypes['User'] | null; // User
    authorId: number | null; // Int
    categories: NexusGenRootTypes['Category'][]; // [Category!]!
    comments: NexusGenRootTypes['Comment'][]; // [Comment!]!
    content: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    keywords: string[]; // [String!]!
    published: boolean; // Boolean!
    tags: NexusGenRootTypes['Tag'][]; // [Tag!]!
    title: string; // String!
    uppercaseTitle: string | null; // String
  }
  Profile: { // field return type
    bio: string; // String!
    id: number; // Int!
    user: NexusGenRootTypes['User']; // User!
  }
  Query: { // field return type
    categories: NexusGenRootTypes['Category'][]; // [Category!]!
    category: NexusGenRootTypes['Category'] | null; // Category
    comment: NexusGenRootTypes['Comment'] | null; // Comment
    comments: NexusGenRootTypes['Comment'][]; // [Comment!]!
    countPosts: number | null; // Int
    countUsers: number | null; // Int
    post: NexusGenRootTypes['Post'] | null; // Post
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    profile: NexusGenRootTypes['Profile'] | null; // Profile
    profiles: NexusGenRootTypes['Profile'][]; // [Profile!]!
    tag: NexusGenRootTypes['Tag'] | null; // Tag
    tags: NexusGenRootTypes['Tag'][]; // [Tag!]!
    user: NexusGenRootTypes['User'] | null; // User
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  Tag: { // field return type
    name: string; // String!
  }
  User: { // field return type
    email: string; // String!
    firstName: string; // String!
    id: number; // Int!
    lastName: string; // String!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    profile: NexusGenRootTypes['Profile'] | null; // Profile
    role: NexusGenEnums['Role']; // Role!
  }
}

export interface NexusGenFieldTypeNames {
  BatchPayload: { // field return type name
    count: 'Int'
  }
  Category: { // field return type name
    id: 'Int'
    name: 'String'
    posts: 'Post'
  }
  Comment: { // field return type name
    content: 'String'
    id: 'Int'
    post: 'Post'
    postId: 'Int'
    title: 'String'
  }
  Mutation: { // field return type name
    createCategory: 'Category'
    createComment: 'Comment'
    createDraft: 'Post'
    createPost: 'Post'
    createProfile: 'Profile'
    createTag: 'Tag'
    createUser: 'User'
    deleteCategories: 'BatchPayload'
    deleteCategory: 'Category'
    deleteComment: 'Comment'
    deleteComments: 'BatchPayload'
    deletePost: 'Post'
    deletePosts: 'BatchPayload'
    deleteProfile: 'Profile'
    deleteProfiles: 'BatchPayload'
    deleteTag: 'Tag'
    deleteTags: 'BatchPayload'
    deleteUser: 'User'
    deleteUsers: 'BatchPayload'
    updateCategories: 'BatchPayload'
    updateCategory: 'Category'
    updateComment: 'Comment'
    updateComments: 'BatchPayload'
    updatePost: 'Post'
    updatePosts: 'BatchPayload'
    updateProfile: 'Profile'
    updateProfiles: 'BatchPayload'
    updateTag: 'Tag'
    updateTags: 'BatchPayload'
    updateUser: 'User'
    updateUsers: 'BatchPayload'
  }
  Post: { // field return type name
    author: 'User'
    authorId: 'Int'
    categories: 'Category'
    comments: 'Comment'
    content: 'String'
    createdAt: 'DateTime'
    id: 'Int'
    keywords: 'String'
    published: 'Boolean'
    tags: 'Tag'
    title: 'String'
    uppercaseTitle: 'String'
  }
  Profile: { // field return type name
    bio: 'String'
    id: 'Int'
    user: 'User'
  }
  Query: { // field return type name
    categories: 'Category'
    category: 'Category'
    comment: 'Comment'
    comments: 'Comment'
    countPosts: 'Int'
    countUsers: 'Int'
    post: 'Post'
    posts: 'Post'
    profile: 'Profile'
    profiles: 'Profile'
    tag: 'Tag'
    tags: 'Tag'
    user: 'User'
    users: 'User'
  }
  Tag: { // field return type name
    name: 'String'
  }
  User: { // field return type name
    email: 'String'
    firstName: 'String'
    id: 'Int'
    lastName: 'String'
    posts: 'Post'
    profile: 'Profile'
    role: 'Role'
  }
}

export interface NexusGenArgTypes {
  Category: {
    posts: { // args
      after?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      before?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Mutation: {
    createCategory: { // args
      data: NexusGenInputs['CategoryCreateInput']; // CategoryCreateInput!
    }
    createComment: { // args
      data: NexusGenInputs['CommentCreateInput']; // CommentCreateInput!
    }
    createDraft: { // args
      authorId: string; // String!
      content?: string | null; // String
      title: string; // String!
    }
    createPost: { // args
      data: NexusGenInputs['PostCreateInput']; // PostCreateInput!
    }
    createProfile: { // args
      data: NexusGenInputs['ProfileCreateInput']; // ProfileCreateInput!
    }
    createTag: { // args
      data: NexusGenInputs['TagCreateInput']; // TagCreateInput!
    }
    createUser: { // args
      data: NexusGenInputs['UserCreateInput']; // UserCreateInput!
    }
    deleteCategories: { // args
      where?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
    }
    deleteCategory: { // args
      where: NexusGenInputs['CategoryWhereUniqueInput']; // CategoryWhereUniqueInput!
    }
    deleteComment: { // args
      where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
    }
    deleteComments: { // args
      where?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
    }
    deletePost: { // args
      where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
    }
    deletePosts: { // args
      where?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    }
    deleteProfile: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    deleteProfiles: { // args
      where?: NexusGenInputs['ProfileWhereInput'] | null; // ProfileWhereInput
    }
    deleteTag: { // args
      where: NexusGenInputs['TagWhereUniqueInput']; // TagWhereUniqueInput!
    }
    deleteTags: { // args
      where?: NexusGenInputs['TagWhereInput'] | null; // TagWhereInput
    }
    deleteUser: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    deleteUsers: { // args
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
    updateCategories: { // args
      data: NexusGenInputs['CategoryUpdateManyMutationInput']; // CategoryUpdateManyMutationInput!
      where?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
    }
    updateCategory: { // args
      data: NexusGenInputs['CategoryUpdateInput']; // CategoryUpdateInput!
      where: NexusGenInputs['CategoryWhereUniqueInput']; // CategoryWhereUniqueInput!
    }
    updateComment: { // args
      data: NexusGenInputs['CommentUpdateInput']; // CommentUpdateInput!
      where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
    }
    updateComments: { // args
      data: NexusGenInputs['CommentUpdateManyMutationInput']; // CommentUpdateManyMutationInput!
      where?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
    }
    updatePost: { // args
      data: NexusGenInputs['PostUpdateInput']; // PostUpdateInput!
      where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
    }
    updatePosts: { // args
      data: NexusGenInputs['PostUpdateManyMutationInput']; // PostUpdateManyMutationInput!
      where?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    }
    updateProfile: { // args
      data: NexusGenInputs['ProfileUpdateInput']; // ProfileUpdateInput!
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    updateProfiles: { // args
      data: NexusGenInputs['ProfileUpdateManyMutationInput']; // ProfileUpdateManyMutationInput!
      where?: NexusGenInputs['ProfileWhereInput'] | null; // ProfileWhereInput
    }
    updateTag: { // args
      data: NexusGenInputs['TagUpdateInput']; // TagUpdateInput!
      where: NexusGenInputs['TagWhereUniqueInput']; // TagWhereUniqueInput!
    }
    updateTags: { // args
      data: NexusGenInputs['TagUpdateManyMutationInput']; // TagUpdateManyMutationInput!
      where?: NexusGenInputs['TagWhereInput'] | null; // TagWhereInput
    }
    updateUser: { // args
      data: NexusGenInputs['UserUpdateInput']; // UserUpdateInput!
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    updateUsers: { // args
      data: NexusGenInputs['UserUpdateManyMutationInput']; // UserUpdateManyMutationInput!
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
  }
  Post: {
    categories: { // args
      after?: NexusGenInputs['CategoryWhereUniqueInput'] | null; // CategoryWhereUniqueInput
      before?: NexusGenInputs['CategoryWhereUniqueInput'] | null; // CategoryWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    comments: { // args
      after?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      before?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    tags: { // args
      after?: NexusGenInputs['TagWhereUniqueInput'] | null; // TagWhereUniqueInput
      before?: NexusGenInputs['TagWhereUniqueInput'] | null; // TagWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Query: {
    categories: { // args
      after?: NexusGenInputs['CategoryWhereUniqueInput'] | null; // CategoryWhereUniqueInput
      before?: NexusGenInputs['CategoryWhereUniqueInput'] | null; // CategoryWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['CategoryOrderByInput'][] | null; // [CategoryOrderByInput!]
      where?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
    }
    category: { // args
      where: NexusGenInputs['CategoryWhereUniqueInput']; // CategoryWhereUniqueInput!
    }
    comment: { // args
      where: NexusGenInputs['CommentWhereUniqueInput']; // CommentWhereUniqueInput!
    }
    comments: { // args
      after?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      before?: NexusGenInputs['CommentWhereUniqueInput'] | null; // CommentWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['CommentOrderByInput'][] | null; // [CommentOrderByInput!]
      where?: NexusGenInputs['CommentWhereInput'] | null; // CommentWhereInput
    }
    countPosts: { // args
      published: boolean; // Boolean!
      title?: string | null; // String
    }
    countUsers: { // args
      firstName?: string | null; // String
      lastName?: string | null; // String
    }
    post: { // args
      where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
    }
    posts: { // args
      after?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      before?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['PostOrderByInput'][] | null; // [PostOrderByInput!]
      where?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    }
    profile: { // args
      where: NexusGenInputs['ProfileWhereUniqueInput']; // ProfileWhereUniqueInput!
    }
    profiles: { // args
      after?: NexusGenInputs['ProfileWhereUniqueInput'] | null; // ProfileWhereUniqueInput
      before?: NexusGenInputs['ProfileWhereUniqueInput'] | null; // ProfileWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['ProfileOrderByInput'][] | null; // [ProfileOrderByInput!]
      where?: NexusGenInputs['ProfileWhereInput'] | null; // ProfileWhereInput
    }
    tag: { // args
      where: NexusGenInputs['TagWhereUniqueInput']; // TagWhereUniqueInput!
    }
    tags: { // args
      after?: NexusGenInputs['TagWhereUniqueInput'] | null; // TagWhereUniqueInput
      before?: NexusGenInputs['TagWhereUniqueInput'] | null; // TagWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['TagOrderByInput'][] | null; // [TagOrderByInput!]
      where?: NexusGenInputs['TagWhereInput'] | null; // TagWhereInput
    }
    user: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    users: { // args
      after?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      before?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['UserOrderByInput'][] | null; // [UserOrderByInput!]
      where?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    }
  }
  User: {
    posts: { // args
      after?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      before?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: types.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
    /**
     * The complexity for an individual field. Return a number
     * or a function that returns a number to specify the
     * complexity for this field.
     */
    complexity?: QueryComplexity<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
}