---
env:
  browser: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - simple-import-sort
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
ignorePatterns:
  - src/**/*.d.ts
rules:
  prettier/prettier: error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
