version: "3.7"
services:
  mysql-db:
    image: "mysql:latest"
    container_name: mysql-db
    ports:
      - 3306:3306
    networks:
      - db_net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ='Asia/Seoul'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
networks:
  db_net:

volumes:
  docker:
