---
env:
  browser: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
rules:
  no-unused-vars: off
  prettier/prettier: error
